version: '3.8'
services:
  api:
    build: .
    container_name: nest-api
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=postgresql://postgres:docker@pg-db:5432/local_db?schema=public
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    entrypoint:
      [
        'sh',
        '-c',
        'npx prisma generate && npx prisma migrate deploy && npm run start:dev',
      ]

  db:
    image: postgres:16
    container_name: pg-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=local_db
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
